### ISSUE TITLE
Setup kanban board

### ISSUE THREAD

**Issue by shasherazi** [shasherazi/library#21]
The project (kanban board) link: https://github.com/users/shasherazi/projects/1

We are two people in this project. Me and @Shakir-Hussain12

**Comment by shasherazi** [comment]
Yeah, my bad. I forgot to make it public 😅

**Comment by julie-ify** [comment]
## Hi @shasherazi and @Shakir-Hussain12,

Good job so far!

## Highlights!
- Descriptive pull request ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Choose who is Student A and Student B and assign your tasks based on that. Also ensure the group tasks are assigned.

  ![andre-assigned](https://user-images.githubusercontent.com/81468675/217013670-358eade2-7f6b-4bc2-a0fa-9659639cb5a2.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by huseyinbiyik** [comment]
Hi @shasherazi and @Shakir-Hussain12,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Great implementation of the requested changes of previous reviewers 🕸️


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
